USE sanjose_police_calls;

-- Populate dim_calltype
INSERT IGNORE INTO dim_calltype (CALLTYPE_CODE, CALL_TYPE)
SELECT DISTINCT CALLTYPE_CODE, CALL_TYPE
FROM policecalls2025_2
WHERE CALLTYPE_CODE IS NOT NULL;

-- Populate dim_disposition
INSERT IGNORE INTO dim_disposition (FINAL_DISPO_CODE, FINAL_DISPO)
SELECT DISTINCT FINAL_DISPO_CODE, FINAL_DISPO
FROM policecalls2025_2
WHERE FINAL_DISPO_CODE IS NOT NULL;
